### ISSUE TITLE
reverse_lazy

### ISSUE THREAD

**Issue by fgau** [shymonk/django-datatable#11]
hi shymonk, I'm not able to run your example with the reverse_lazy option. can you please write a full example with urls.py, tables.py and views.py? that would be quite helpful. thx!

**Comment by shymonk** [comment]
Tell me which version of Django do you use, i will write a example for you.

**Comment by fgau** [comment]
I'm using Django version 1.7 and Python 2.7.9. Thanks for your help!

**Comment by shymonk** [comment]
Apologize for the mistake in README.
See the latest example on master branch.

**Comment by fgau** [comment]
Thank you very much for the example app. Now all working fine here. Great app!!!
