### ISSUE TITLE
problem if app runnnig with ssl webserver enviroment

### ISSUE THREAD

**Issue by fgau** [shymonk/django-datatable#12]
hi,
first of all, great app!
in  django-datatable/table/templates/table/table.html you hardcoded <script src="http://cdn.datatables.net/1.10.0/js/jquery.dataTables.min.js" type="text/javascript"></script> with http. with that, the table is not showing with ssl setup. please replace it with a CDN reference like here (http://datatables.net/manual/installation#CDN).
thanks.

**Comment by shymonk** [comment]
well, feel free to fork and make a pull-request to fix it.
it's very helpful.

**Comment by shymonk** [comment]
So, this issue can be closed? @fgau

**Comment by fgau** [comment]
Yes! Thanks for merging my pull request.
