### ISSUE TITLE
LinkColumn

### ISSUE THREAD

**Issue by ragrawal** [shymonk/django-datatable#15]
Hi 

This is very useful package and I was able to get basic stuff working pretty easily. However I am having hard time using LinkColumn functionality. Can you provide few more examples on how to use LinkColumn and ImageLink etc. 

Thanks

Ritesh

**Comment by shymonk** [comment]
@ragrawal apologize for late response. 
I just added example for LinkColumn, please checkout.
I designed `LinkColumn` for the features such as `Edit`, `Detail` for CMS, so you must pass `viewname` and `args` into `Link` class to reverse url.
For other requirements, you can inherit `Link` class and hardcode links.
