### ISSUE TITLE
Strange message when ordering

### ISSUE THREAD

**Issue by mpena2099** [shymonk/django-datatable#24]
Hi!

Look that: 
![ordering](https://cloud.githubusercontent.com/assets/1200886/10721533/70deeb6c-7b8c-11e5-96cc-044df234a0a9.png)

It's a kind of "loading" message or what? If so, where could I change it?

Thanks!
Mauricio

**Comment by shymonk** [comment]
Yeah, this is the content of `sProcessing` option for dataTable interface in javascript.
I will replace the message with 'Loading' as soon as possible.

**Comment by mpena2099** [comment]
To do in future: a way to easily translate that message in other languages. (Localization support?)

Thanks!
Mauricio
