### ISSUE TITLE
errors when installing on Mac

### ISSUE THREAD

**Issue by nilanjenator** [shymonk/django-datatable#32]
I get a bunch of syntax errors on the Mac.  I cloned over https.  Not sure if it matters.  
Tried cloning using ssh - same problem.  I also can't seem to use the example project

  File "build/bdist.macosx-10.10-x86_64/egg/table/tests/test_columns.py", line 124
    column1 = MonthsColumn(None, date(2012, 12, 18), date(2013, 07, 01))
                                                                 ^
SyntaxError: invalid token

byte-compiling build/bdist.macosx-10.10-x86_64/egg/table/tests/test_tables.py to test_tables.cpython-34.pyc
byte-compiling build/bdist.macosx-10.10-x86_64/egg/table/tests/test_views.py to test_views.cpython-34.pyc
byte-compiling build/bdist.macosx-10.10-x86_64/egg/table/tests/test_widgets.py to test_widgets.cpython-34.pyc
byte-compiling build/bdist.macosx-10.10-x86_64/egg/table/urls.py to urls.cpython-34.pyc
byte-compiling build/bdist.macosx-10.10-x86_64/egg/table/utils.py to utils.cpython-34.pyc
  File "build/bdist.macosx-10.10-x86_64/egg/table/utils.py", line 45
    except Exception, e:
                    ^
SyntaxError: invalid syntax

**Comment by shymonk** [comment]
Well, it's really weird. I built this application on my Macbook as well.
Try the following commands, let me know the output.
```
$ cd django-datatable/example
$ python manage.py runserver
```
