### ISSUE TITLE
Warning deprecated in reverse url

### ISSUE THREAD

**Issue by rodolphopivetta** [shymonk/django-datatable#34]
When use linkcolumn, this warning appears:
```
/local/lib/python2.7/site-packages/django_datatable-0.1.4-py2.7.egg/table/columns/linkcolumn.py:72: RemovedInDjango110Warning: Reversing by dotted path is deprecated.
  return reverse(self.viewname, **params)
```

**Comment by rodolphopivetta** [comment]
This too.

```
/local/lib/python2.7/site-packages/django_datatable-0.1.4-py2.7.egg/table/templatetags/table_tags.py:18: RemovedInDjango110Warning: render() must be called with a dict, not a Context.
  return t.render(context)
```

**Comment by shymonk** [comment]
For the 1st issue, see https://docs.djangoproject.com/en/1.9/ref/urlresolvers/#reverse
    
> Deprecated since version 1.8:
> The ability to reverse using the Python path, e.g. reverse('news.views.archive'), has been deprecated.

**Comment by shymonk** [comment]
For the 2nd, see the comments of function `render()` in source file https://docs.djangoproject.com/en/1.9/_modules/django/template/backends/django/

**Comment by rodolphopivetta** [comment]
About 1st issue, sorry, I really didn't see that the error was mine.

About 2st issue, you can consider change in [template_tags.py](https://github.com/shymonk/django-datatable/blob/master/table/templatetags/table_tags.py#L16) the code:

```python
def render(self, context):
    table = self.table.resolve(context)
    context = Context({'table': table})
    t = template.loader.get_template(self.template_name)
    return t.render(context)
```

by
```python
def render(self, context):
    table = self.table.resolve(context)
    context = {'table': table}
    t = template.loader.get_template(self.template_name)
    return t.render(context)
```
like say in warning message.

**Comment by rodolphopivetta** [comment]
About 1st issue, sorry, I really didn't see that the error was mine.

About 2st issue, due to the support of other versions you have not changed the code yet?

**Comment by shymonk** [comment]
Exactly, i can't remove `Context`because it will raise Exception in django 1.5.
