### ISSUE TITLE
How to add CheckboxColumn as checked on base of field value

### ISSUE THREAD

**Issue by ReenSami** [shymonk/django-datatable#37]
Please provide one working example of checkbox column selected on base of field value .
And can I perform any action on this checkbox like enable and disable.
Or How can I add Image Link columns on base of field value, If field value true call view A  and image A ,if field value false call view B and image B,

**Comment by shymonk** [comment]
Thanks, i realized  this is a big issue for `CheckboxColumn`.
I have fixed it by making `CheckboxColumn` related to a boolean model field, please checkout the lastest revision on master.
Moreover, you need to create a new `django view` to handle checkbox status with some `js` snippets.

**Comment by ReenSami** [comment]
Thanks shymonk for your quick response. 
I am new to django, I want to know how can i do something like this
amountToMerchant= Column(header=u'Amount to Merchant', field=(float('orderCost')-float('srviceFee')))
