### ISSUE TITLE
Py3 support

### ISSUE THREAD

**Issue by matheusjardimb** [shymonk/django-datatable#42]
when django-datatable==0.1.5 some files (like tables/utils.py) aren't py3 compatible. 
The code seems fixed in the repo but no version was published whit that changes

**Comment by matheusjardimb** [comment]
`pip install git+ssh://git@github.com/shymonk/django-datatable.git` solved the issue, but still a new version would be better

**Comment by shymonk** [comment]
@matheusjardimb Thanks for your feedback, checkout v0.2.0 on pypi please.
