### ISSUE TITLE
How to include the Copy, CSV, Excel, PDF and Print Buttons 

### ISSUE THREAD

**Issue by shalomz** [shymonk/django-datatable#64]
I have been trying to figure out how I can include the Copy, CSV, Excel, PDF and Print Buttons as shown in <https://datatables.net/extensions/buttons/examples/html5/filename.html> .
Any help would be highly accepted.

**Comment by shymonk** [comment]
Hi, @shalomz, sorry for delayed response.
I take two days to make a new release to support this feature. Check out the `ButtonsExtensionTable` of latest code case please.
Oneline demo is here: https://www.shymonk.com/django-datatable/extensions/buttons/

**Comment by shalomz** [comment]
Thanks @shymonk it works super fine now.
