### ISSUE TITLE
Is possible do customize queryset?

### ISSUE THREAD

**Issue by mosesmeirelles** [shymonk/django-datatable#67]
At the point I haven't found this option at wiki, I was trying to find this option on source code but I'm not an expert. Is possible to specify a custom queryset to fetch data from model?
This package is awesome, btw :)

**Comment by shymonk** [comment]
@mshmeirelles it's quite easy, see https://github.com/shymonk/django-datatable#queryset

**Comment by mosesmeirelles** [comment]
Nice @shymonk ! I really hadn't seen this part of documentation o.o I feel embarrassed. I'll read more carefully next time, thanks for your patience!
